CREATE TABLE IF NOT EXISTS mpa_rates
(
	mpa_rate_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	mpa_rate_name VARCHAR(7)
);

CREATE TABLE IF NOT EXISTS films
(
	film_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	film_name VARCHAR(63),
	description VARCHAR(200),
	release_date DATE,
	duration_in_minutes INT,
	mpa_rate_id INT REFERENCES mpa_rates(mpa_rate_id)
);

CREATE TABLE IF NOT EXISTS users
(
	user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_name VARCHAR(255),
	login VARCHAR(255),
	email VARCHAR(255),
	birthday DATE
);

CREATE TABLE IF NOT EXISTS likes
(
	film_id INT REFERENCES films(film_id),
	user_id INT REFERENCES users(user_id),
	PRIMARY KEY(film_id, user_id)	
);

CREATE TABLE IF NOT EXISTS friend_links
(
	initiator_user_id INT REFERENCES users(user_id),
	recipient_user_id INT REFERENCES users(user_id),
	confirm BOOL,
	PRIMARY KEY(initiator_user_id, recipient_user_id),
	CHECK (initiator_user_id <> recipient_user_id)
);

CREATE TABLE IF NOT EXISTS genres
(
	genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	genre_name VARCHAR(63)
);

CREATE TABLE IF NOT EXISTS film_genres
(
	film_id INT REFERENCES films(film_id),
	genre_id INT REFERENCES genres(genre_id),
	PRIMARY KEY(film_id, genre_id)	
);

